spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

auth:
  issuer: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      
      