spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

eureka:
  client:
    enabled: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans