server:
  port: 9000

spring:
  application:
    name: auth-server

gateway:
  client-secret: ${GATEWAY_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO