spring:

  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        
auth:
  issuer: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans