server:
  port: 8086

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://mysql:3306/inventorydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

inventory:
  available: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.security: INFO