spring:
  kafka:
    bootstrap-servers: kafka:29092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans