server:
  port: 8087

spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.security: INFO