server:
  port: 8082

spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO