apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: secureflow

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: <your-root-password>
  MYSQL_DATABASE: secureflow
  MYSQL_USER: secureflow
  MYSQL_PASSWORD: <your-mysql-password>
