apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: secureflow
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: secureflow/user-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: CONFIG_SERVER
              value: http://config-server:8888
