apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: secureflow
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: secureflow/inventory-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: CONFIG_SERVER
              value: http://config-server:8888
