spring:
  application:
    name: product-service

  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}

  management:
    endpoint:
      health:
        show-details: always