input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => {
        "[@metadata][index]" => "secureflow-%{[service]}"
      }
    }
  } else {
    mutate {
      add_field => {
        "[@metadata][index]" => "secureflow-logs"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}